### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by rkinsella** [samiff/yaynaynay#2]
I was looking to make my own overlay extension. I was wondering if you could help me set it up. I can definitely figure out the reset, just not sure on how to to set it all up.

**Comment by samiff** [comment]
I could try :wink: A few developers are having problems right now using `webpack` to build their projects, so I can't really recommend that right now until things are more clear.

What did you have a question about? Also, I've learned a lot by reading the [dev forums](https://discuss.dev.twitch.tv/c/extensions).

**Comment by rkinsella** [comment]
Just in general setting it up. I've looked into the twitch extension provided by Twitch, boilerplate and also Muxy. Couldn't figure out how to set up boilerplate on Windows and Muxy is for creating extensions for their own extension. I know node.js just honestly have no clue where to start. Your project looked like a good starting point.

**Comment by samiff** [comment]
Most simply there are three different HTML files or views you can make: viewer (the video overlay or panel), live_config (what broadcasters see on their dashboard), and config (what is seen in the configuration view). The only thing I did different from the boilerplate was use ngrok instead of setting up the certs on my machine. Just take things one at a time, and make sure you can simply output some simple HTML to the different views. If you're running into a specific problem, I'm on Windows too and will try to help.
